services:
    postgresql:
        image: postgres:17
        container_name: hexagonal-postgresql
        environment:
            POSTGRES_DB: HexagonalSkeleton
            POSTGRES_USER: hexagonal_user
            POSTGRES_PASSWORD: hexagonal_password
        ports:
            - "5432:5432"
        volumes:
            - postgresql_data:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U hexagonal_user -d HexagonalSkeleton"]
            interval: 10s
            timeout: 5s
            retries: 3
            start_period: 30s
        restart: unless-stopped

volumes:
    postgresql_data:
